### ISSUE TITLE
Limit grey box width around management photos

### ISSUE THREAD

**Issue by julehen** [sinnerschrader/website#112]
**Issue**
![image](https://cloud.githubusercontent.com/assets/23521409/20799525/c05b93b4-b7e2-11e6-90d1-e249a2ecd6a4.png)

**Comment by marionebl** [comment]
Some questions:
* Should the limit apply to all viewports? We get numerous cases where the grey background fills the remaining space, see screenshots
* According to which rule should this limiting be implemented? Possible:
  * Fixed distance between right boundary of image and grey box, e.g. "
  * Define maximum allowed width for grey box for each viewport 
* @SandyStrobel Could you explain **why** you need this change? E.g.: Which design rules are met better when doing this?

**Comment by kotzendekrabbe** [comment]
@marionebl i just talked with sandy about this. i will fixed it

**Comment by marionebl** [comment]
@kotzendekrabbe Could you document

* What this fix will be
* What the design reasons are

**Comment by SandyStrobel** [comment]
![bildschirmfoto 2016-12-07 um 10 26 11](https://cloud.githubusercontent.com/assets/23631312/20962938/bfcfd86e-bc6b-11e6-8eba-d9a8717144f4.png)
![bildschirmfoto 2016-12-07 um 10 31 38](https://cloud.githubusercontent.com/assets/23631312/20962940/c1582fba-bc6b-11e6-9d3a-0ef24cfee5b6.png)
