### ISSUE TITLE
telephone number rendered as link

### ISSUE THREAD

**Issue by julehen** [sinnerschrader/website#115]
**Actual**
Swipe and Commerce telephone numbers are rendered as links

**OS**: Windows 10 
**Browser**: Edge Version: 38.14393.0.0

![bildschirmfoto 2016-12-01 um 16 42 32](https://cloud.githubusercontent.com/assets/23521409/20800266/325df7ca-b7e5-11e6-9c30-c9194f7829f4.png)

**Expected**
All telephone numbers are rendered as plain text

--- 

**Estimation**
@knisterpeter 5 minutes

**Comment by KnisterPeter** [comment]
It would require a meta entry: `<meta name="format-detection" content="telephone=no">`.
