### ISSUE TITLE
automate icons sprite svg

### ISSUE THREAD

**Issue by julehen** [sinnerschrader/website#117]

**Comment by KnisterPeter** [comment]
@kotzendekrabbe Is this done?

**Comment by kotzendekrabbe** [comment]
no, it's still open

**Comment by marionebl** [comment]
What do we want to achieve exactly?

**Comment by julehen** [comment]
Please make sure that the icons are optimized (https://github.com/svg/svgo) and then generate the sprite (https://www.npmjs.com/package/svg-sprite-generator)
