### ISSUE TITLE
Module_04_Contact List 

### ISSUE THREAD

**Issue by julehen** [sinnerschrader/website#118]
**Actual**
On the viewport around `768px` the sinnerschrader.jobs link creates a visually unpleasing newline

![image](https://cloud.githubusercontent.com/assets/23521409/20802845/a2a70f3c-b7ed-11e6-91a7-2b3ee52d5045.png)

**Expected**
No newline for the link

---
| User | Estimation |
| --- | --- |
| @knisterpeter | 5 minutes |

**Comment by kotzendekrabbe** [comment]
set 2 column later (maybe at 800px or something like this)

**Comment by marionebl** [comment]
I'd suggest we  drop the scheme and `www` subdomain from the link text:

* https://www.sinnerschrader.jobs => sinnerschrader.jobs
* http://www.sinnerschrader.ag => sinnerschrader.ag

**Comment by kotzendekrabbe** [comment]
@marionebl sounds like ab bette solution for me

**Comment by julehen** [comment]
Done.
