### ISSUE TITLE
about/what | Numbers are rendered twice

### ISSUE THREAD

**Issue by julehen** [sinnerschrader/website#119]
The numbers are rendered twice with a tiny offset.

![image](https://cloud.githubusercontent.com/assets/23521409/20803098/5f00a094-b7ee-11e6-8fb5-a47907696e57.png)

![image](https://cloud.githubusercontent.com/assets/23521409/20803121/6bb4d51c-b7ee-11e6-91f8-7b4cae8107dc.png)

**Comment by kotzendekrabbe** [comment]
seems to be iOS only - bug

**Comment by julehen** [comment]
Done.
