### ISSUE TITLE
use font css from cloudfront cdn 

### ISSUE THREAD

**Issue by julehen** [sinnerschrader/website#120]
The used fonts css is availabe at [cloudfront](https://d2rk9tszs3pbpk.cloudfront.net/css/fonts2016.css
).

**Comment by KnisterPeter** [comment]
@helgri Is the cloudfront css the actual font.css?

**Comment by marionebl** [comment]
Is this still relevant? Afaik we have a CDN in place for all assets on https://www.sinnerschrader.com anyway

**Comment by KnisterPeter** [comment]
I would tend to say we have github as CDN.

**Comment by marionebl** [comment]
Closed for inactivity
