### ISSUE TITLE
Add arrow to header modules

### ISSUE THREAD

**Issue by julehen** [sinnerschrader/website#121]
Introduce arrows pointing down on headers to make the difference between teaser and header images transparent to the user.

![image](https://cloud.githubusercontent.com/assets/23521409/20803226/b93cd3de-b7ee-11e6-8337-d947b5d1deef.png)

**Comment by marionebl** [comment]
@SandyStrobel I guess we need a SVG resource for the arrow. Is this the project somewhere? If not: can you provide it? 

Thanks!

**Comment by SandyStrobel** [comment]
Habe ihn hier abgelegt: https://drive.google.com/open?id=0B8w7Ll4VSEYbRGViNGItY0JGclU

**Comment by julehen** [comment]
Not more relevant.
