### ISSUE TITLE
patternplate-hubot replacement or credential-management

### ISSUE THREAD

**Issue by KnisterPeter** [sinnerschrader/website#140]
Currently the patternplate-hubot is a 'blackbox' in the process.
This need a few thoughts and :heart: to streamlin or document the process and handling.

**Comment by marionebl** [comment]
Unfortunately I had to fall back to patternplate-hubot to get the deployments up and running again. I'm in favor of keeping the user around and document it properly.

**Comment by marionebl** [comment]
Won't change this for this setup due to time constraints
