### ISSUE TITLE
New Curved Video

### ISSUE THREAD

**Issue by julehen** [sinnerschrader/website#191]
Curved video exchange.

Video will follow from @julhen.

**Comment by SandyStrobel** [comment]
**New Video here**
smb://szz-f03/s2-ham/25_ZS2-Projekte/20_ZS2_CD-CI/10_SinnerschraderDE/02_Design/S2_Website_2017/Drive_S2_Website/_assets/_Videos/CURVED_Trailer_2017_HD.mp4

We keep our old startscreen
