### ISSUE TITLE
New Design for TUIfly

### ISSUE THREAD

**Issue by julehen** [sinnerschrader/website#201]
We have a new design for the TUIfly case.
Design will follow from Sandy.

**Comment by SandyStrobel** [comment]
We have a new layout and need to change assets in three places.

![case_tui_desk_marked](https://cloud.githubusercontent.com/assets/23631312/23267588/794d59c6-f9eb-11e6-8409-5ad318fc27d1.png)

Two new pics and a new video plus startscreen.

You find new assets here:

**Devices** 
smb://szz-f03/s2-ham/25_ZS2-Projekte/20_ZS2_CD-CI/10_SinnerschraderDE/02_Design/S2_Website_2017/Drive_S2_Website/_assets/Cases/2_TUIfly/2_Module_24_Case1

**Phone**
smb://szz-f03/s2-ham/25_ZS2-Projekte/20_ZS2_CD-CI/10_SinnerschraderDE/02_Design/S2_Website_2017/Drive_S2_Website/_assets/Cases/2_TUIfly/3_Module_22_Story2

**Video**
smb://szz-f03/s2-ham/25_ZS2-Projekte/20_ZS2_CD-CI/10_SinnerschraderDE/02_Design/S2_Website_2017/Drive_S2_Website/_assets/_Videos/s2_website-tuifly_travel booking.mp4

**Startscreen**
smb://szz-f03/s2-ham/25_ZS2-Projekte/20_ZS2_CD-CI/10_SinnerschraderDE/02_Design/S2_Website_2017/Drive_S2_Website/_assets/_Videos/_startscreens/TUIfly_Travel Booking.png
