### ISSUE TITLE
Home — 7_Module_02_Teaser

### ISSUE THREAD

**Issue by SandyStrobel** [sinnerschrader/website#202]
we have a new Picture for NEXT Teaser and also need a new headline / subline position

old picture & headline / subline position

![bildschirmfoto 2017-02-23 um 16 47 26](https://cloud.githubusercontent.com/assets/23631312/23266387/f48668c0-f9e7-11e6-9821-d3461739f84f.png)

new picture & headline / subline position

![beispiel_module_01_hero_desk_home_next](https://cloud.githubusercontent.com/assets/23631312/23266441/186bbac4-f9e8-11e6-9f3e-deb8beab1a89.jpg)
![beispiel_module_01_hero_lap_home_next](https://cloud.githubusercontent.com/assets/23631312/23266440/18697840-f9e8-11e6-95b1-2a3e62a980ef.jpg)
![beispiel_module_01_hero_palm_work_home_next](https://cloud.githubusercontent.com/assets/23631312/23266439/18684cae-f9e8-11e6-8035-4a8a7c0f65a6.jpg)

Find new asset here:
smb://szz-f03/s2-ham/25_ZS2-Projekte/20_ZS2_CD-CI/10_SinnerschraderDE/02_Design/S2_Website_2017/Drive_S2_Website/_assets/Home/7_Module_02_Teaser

**Comment by kotzendekrabbe** [comment]
@julehen @SandyStrobel next time, please with the text - so we could make copy&paste

**Comment by SandyStrobel** [comment]
we keep the old text, so no copy and paste necessary

**Comment by marionebl** [comment]
Solved via #208

**Comment by SandyStrobel** [comment]
we need a new sub- and headline position. 

old / actual positon
![bildschirmfoto 2017-03-14 um 10 09 38](https://cloud.githubusercontent.com/assets/23631312/23893489/eba133b4-089e-11e7-8891-3fb479295c0b.png)


new position
<img width="813" alt="bildschirmfoto 2017-03-14 um 10 18 00" src="https://cloud.githubusercontent.com/assets/23631312/23893692/c686e186-089f-11e7-8d6e-b87744a7414d.png">

**Comment by julehen** [comment]
@Alexpeschel: We need a new sub- and headline position.

**Comment by julehen** [comment]
@Alexpeschel: ready to deploy
