### ISSUE TITLE
Static asset for NEXT is way too big

### ISSUE THREAD

**Issue by timbru31** [sinnerschrader/website#221]
We deliver a 3mb big background image on production:
https://sinnerschrader.com/static/images/backgrounds/module_01_hero_desk_next.jpg

## Actual behaviour

Visit page, notice that for the NEXT a 3mb big image is loaded.
<img width="961" alt="screen shot 2017-03-23 at 11 56 27" src="https://cloud.githubusercontent.com/assets/838003/24244570/cc836da8-0fbf-11e7-97d4-be5d7db09599.png">

## Expected behaviour

This could be compressed 😄 
Google says we could save 2.79mb according to page speed. Has to be done in the asset project.

**Comment by SandyStrobel** [comment]
there are new assets in our folder: smb://szz-f03/s2-ham/25_ZS2-Projekte/20_ZS2_CD-CI/10_SinnerschraderDE/02_Design/S2_Website_2017/Drive_S2_Website/_assets/Home/7_Module_02_Teaser

**Comment by Alexpeschel** [comment]
folder only contains desktop size

**Comment by julehen** [comment]
@SandyStrobel the mobile design is missing.
