### ISSUE TITLE
Module 27 Case 4 / > 1024

### ISSUE THREAD

**Issue by SandyStrobel** [sinnerschrader/website#236]
Second text field should be new positioned at x 598

## Actual behaviour

![bildschirmfoto 2017-04-04 um 14 07 28](https://cloud.githubusercontent.com/assets/23631312/24655815/13482d6c-1940-11e7-849e-adee05072a60.png)

## Expected behaviour

![module_27_case4](https://cloud.githubusercontent.com/assets/23631312/24655822/1a5fed9c-1940-11e7-821f-7678967fcfb7.png)

**Comment by Alexpeschel** [comment]
fixed in #214
