### ISSUE TITLE
Menu cut off on scrolling (iOS)

### ISSUE THREAD

**Issue by Dangoo** [sinnerschrader/website#24]
While having the menu open and scrolling down the page, the menu overlay is rendered too short when browser navigation bars shrink (See image below).

Tested on iOS 10 Safari (and Chrome)

![img_7882](https://cloud.githubusercontent.com/assets/1252204/20437787/9ef6a2fe-adb5-11e6-940a-0db737aec1e7.PNG)

**Comment by kotzendekrabbe** [comment]
thanks, would be nice to receive a pull request

**Comment by marionebl** [comment]
![number-24-ios](https://cloud.githubusercontent.com/assets/4248851/20457831/3f309c00-ae94-11e6-8c1d-39a071d4975b.gif)

**Comment by Dangoo** [comment]
It seems like Safari is not rendering the parts off the element which is fix positioned.
Tested my fix in Xcode Beta with iOS 10 SDK. After testing in Xcode Stable with iOS SDK and on iPhone I get the same behaviour as @marionebl.

**Comment by marionebl** [comment]
@Dangoo Are you still on this?

**Comment by Dangoo** [comment]
Yepp, but will take some time.

**Comment by tosviol** [comment]
I've tested this on IOS 10.3 on both Safari and Chrome. I think they might have fixed this behavior as the navigation will just snap back to the desired height right after the scrolling stops. Or is this the same behavior as before?

![s2_ios_menu_fixed](https://cloud.githubusercontent.com/assets/138926/24954463/c6ace01a-1f7f-11e7-8488-5326cfa0c0f6.gif)
