### ISSUE TITLE
AboutWhy: graphic "Staying ahead of the curve." is missing | Internet Explorer 11

### ISSUE THREAD

**Issue by julehen** [sinnerschrader/website#25]
AboutWhy: graphic "Staying ahead of the curve." is missing

Windows Laptop
Browser: Internet Explorer 11; Version: 11.447.14393.0

![img_0095](https://cloud.githubusercontent.com/assets/23521409/20438388/c07fd33a-adb7-11e6-8d41-f77ff608b4ba.JPG)

**Comment by kotzendekrabbe** [comment]
ie11 will be droped from browsermatrix
