### ISSUE TITLE
Duplicate Company

### ISSUE THREAD

**Issue by kontez** [sinnerschrader/website#279]
In https://sinnerschrader.jobs/en/ under the "Company" Section there is a duplicate, SinnerSchrader and Sinnerschrader.

![sinnerschrader](https://cloud.githubusercontent.com/assets/7038941/25434700/a3bf5ff6-2a8d-11e7-9666-bd054c4dafc9.png)

**Comment by marionebl** [comment]
sinnerschrader.jobs currently is not part of this OSS project but a distinct, closed-source application
