### ISSUE TITLE
Drop IE11 from Browser Matrix

### ISSUE THREAD

**Issue by marionebl** [sinnerschrader/website#49]
There is confusion in the project team about wether IE11 is to be supported. Unknowingly of the latest development I added it to the Browser Matrix with #47. 

Let's collect here

* If we should drop it from the matrix
* What the IE11 issues are
* If we act on them

---
Connected:
* https://github.com/sinnerschrader/sinnerschrader-website/issues/25

**Comment by kotzendekrabbe** [comment]
in the last two month, we've only 4,6% of ie11 users - if this information helps.

ie11 issues:
- external svg icon sprite (doesn't work in ie11)
-- possible fix: inline svg. we've only a few icons, so this should be ok

offer:
we add ie11 as b-browser

**Comment by marionebl** [comment]
Drop IE 11

**Comment by marionebl** [comment]
B-Grade Support

**Comment by marionebl** [comment]
Vote via +1 on the comments above
