### ISSUE TITLE
documentation and comments

### ISSUE THREAD

**Issue by kotzendekrabbe** [sinnerschrader/website#64]
- add workflow documentation
- add inline comments/documentation in template files
-- for modules
-- for elements

**Comment by KnisterPeter** [comment]
https://github.com/sinnerschrader/sinnerschrader-website/wiki/Workflows

**Comment by marionebl** [comment]
As the workflow goes I went ahead and made patternplate-hubot more human-friendly.

https://github.com/sinnerschrader/sinnerschrader-website/pull/127

This should make it easier to grasp what is going on with:

* source PRs against master
* PRs triggering deployments to staging
* PRs triggering actual production deployments

**Comment by KnisterPeter** [comment]
@marionebl Will you build a technical flowchart?

**Comment by marionebl** [comment]
@KnisterPeter yes.

**Comment by marionebl** [comment]
patternplate-hubot is pretty chatty now. I am whipping up a replacement setup for schlump, so this is obsolete in other regards
