### ISSUE TITLE
Filter zurückgesetzt

### ISSUE THREAD

**Issue by LucieLucieLucie** [sinnerschrader/website#7]
Wenn man auf eurer sinnerschrader.jobs Seite Filter verwendet, sich einen Job anguckt und dann (mit dem Browser Backbutton) wieder zurück zur Jobliste geht, sind alle Filter verschwunden und man muss sie neu eingeben. 
Mit dem Android default Internet Browser

**Comment by t0rbn** [comment]
Reproduzierbar mit Chrome 56.0.2914.3 dev Desktop auf 360px Breite skaliert

**Comment by kotzendekrabbe** [comment]
Danke für den Hinweis, wir werden uns drum kümmern

**Comment by marionebl** [comment]
This is a bug with the `sinnerschrader.jobs` application, which is a distinct, non-OSS project.
